"""Native-backed partner display-key allowlists, translated using the APK MO.

Only entity names and skill descriptions are selected; not the full game catalog.
Native name switch: 0x10C5ED8. Variant switch: 0x14BE9F0 / chunk 0x174AE88.
Runtime-conditional suffixes are intentionally not presented as static save state.
"""

PARTNER_NAME_KEYS: dict[str, tuple[str, ...]] = {
    "hikari": ("Hikari",),
    "tairitsu": ("Tairitsu",),
    "kou": ("Kou",),
    "sapphire": ("Sapphire",),
    "lethe": ("Lethe",),
    "hikari_tairitsu_reunion": ("Hikari & Tairitsu", "Reunion"),
    "tairitsu_yugamu": ("Tairitsu", "Axium"),
    "tairitsu_grievous_lady": ("Tairitsu", "Grievous Lady"),
    "stella": ("Stella",),
    "hikari_fisica_quon": ("Hikari & Fisica",),
    "ilith": ("Ilith",),
    "eto": ("Eto",),
    "luna": ("Luna",),
    "shirabe": ("Shirabe",),
    "hikari_zero": ("Hikari", "Zero"),
    "hikari_fracture": ("Hikari", "Fracture"),
    "hikari_summer": ("Hikari", "Summer"),
    "tairitsu_summer": ("Tairitsu", "Summer"),
    "tairitsu_trin": ("Tairitsu & Trin",),
    "ayu": ("Ayu",),
    "eto_luna_winter": ("Eto & Luna", "Winter"),
    "yume": ("Yume",),
    "hikari_seine": ("Hikari & Seine",),
    "saya": ("Saya",),
    "gl_penguin": ("Tairitsu & Chuni Penguin", "Grievous Lady"),
    "chuni_penguin": ("Chuni Penguin",),
    "haruna": ("Haruna",),
    "nono": ("Nono",),
    "mtaxxx": ("Pandora Nemesis", "MTA-XXX"),
    "mda21": ("Regulus", "MDA-21"),
    "kanae": ("Kanae",),
    "hikari_ost": ("Hikari", "Fantasia"),
    "tairitsu_ost": ("Tairitsu", "Sonata"),
    "sia": ("Sia",),
    "doroc": ("DORO*C",),
    "tairitsu_tempest": ("Tairitsu", "Tempest"),
    "brilliante": ("Brillante", "E/S Primera"),
    "ilith_summer": ("Ilith", "Summer"),
    "saya_ost": ("Saya", "Etude"),
    "alice_tenniel": ("Alice & Tenniel",),
    "luna_mia": ("Luna & Mia",),
    "areus": ("Areus",),
    "seele": ("Seele",),
    "isabelle": ("Isabelle",),
    "mir": ("Mir",),
    "lagrange": ("Lagrange",),
    "linka": ("Linka",),
    "nami": ("Nami",),
    "saya_elizabeth": ("Saya & Elizabeth",),
    "lily": ("Lily",),
    "kanae_midsummer": ("Kanae", "Midsummer"),
    "alice_tenniel_ost": ("Alice & Tenniel", "Minuet"),
    "tairitsu_ost_elegy": ("Tairitsu", "Elegy"),
    "marija": ("Marija",),
    "vita": ("Vita",),
    "hikari_fatalis": ("Hikari", "Fatalis"),
    "saki": ("Saki",),
    "setsuna": ("Setsuna",),
    "amane": ("Amane",),
    "kou_winter": ("Kou", "Winter"),
    "lagrange_aria_ost": ("Lagrange", "Aria"),
    "lethe_apophenia": ("Lethe", "Apophenia"),
    "shama": ("Shama", "UNiVERSE"),
    "milk": ("Milk", "UNiVERSE"),
    "shikoku": ("Shikoku",),
    "mika": ("Mika Yurisaki",),
    "mithra": ("Mithra Tercera",),
    "toa": ("Toa Kozukata",),
    "nami_twilight": ("Nami", "Twilight"),
    "ilith_ivy": ("Ilith & Ivy",),
    "hikari_vanessa": ("Hikari & Vanessa",),
    "maya": ("Maya",),
    "intruder": ("Insight",),
    "luin": ("Luin",),
    "vita_cadenza_ost": ("Vita", "Cadenza"),
    "aichan": ("Ai-chan",),
    "luna_ilot": ("Luna & Ilot",),
    "eto_hoppe": ("Eto & Hoppe",),
    "nell": ("Forlorn", "Ascendant - 6th Seeker"),
    "chinatsu": ("Chinatsu",),
    "tsumugi": ("Tsumugi",),
    "nai": ("Nai",),
    "selene": ("Selene Sheryl", "MIR-203"),
    "salt": ("Salt",),
    "acid": ("Acid",),
    "hikari_selene": ("Hikari & Selene Sheryl", "Fracture & MIR-203"),
    "hikari_clear": ("Hikari & El Clear",),
    "tairitsu_fail": ("Tairitsu & El Fail",),
    "nami_sui": ("Nami & Sui", "Twilight"),
    "nonoka": ("Nonoka",),
    "vita_arc": ("Vita", "Wanderer"),
    "hikari_tairitsu_ans_ost": ("Hikari & Tairitsu[ANS]", "Breakthrough"),
    "hikari_tairitsu_debut": ("Hikari & Tairitsu[ANS]", "Debut"),
    "viim": ("VIIM",),
    "helena": ("Helena",),
    "yuno": ("Yuno",),
    "shirahime_flow": ("Shirahime", "Flow"),
    "saya_konzetsu": ("Saya", "Absolution"),
    "insight_konzetsu": ("Insight", "Nullified"),
    "shirahime": ("Shirahime",),
}


# Native display function 0x1770D90.
# SHA-256: 72e42cb4925655ecfef98bf2dbf92a5ac05145eb005a531c96c11b927a46e6dc.
SKILL_MESSAGE_KEYS: dict[str, tuple[str, ...]] = {
    "audio_gcemptyhit_pack_groovecoaster": (
        "AUDIO - Ad-lib effects on hitting floor lanes\nwhen playing a %2@ song",
    ),
    "ayu_uncap": ("World Mode progress randomly increased\nor decreased between %2@ and %3@",),
    "challenge_fullcombo_0gauge": ("Recollection Gauge set to 0 for LOST notes",),
    "combo_100-frag_1": ("Earn +%@ Fragment(s)\nfor each %2@ combo reached",),
    "eto_uncap": ("World progress increased by\n%@ if a Fragment reward is collected",),
    "frag_plus_10_pack_stellights": ("Earn +%@ Fragments\nwhen playing a Stellights song",),
    "frag_plus_5_side_conflict": ("Earn +%@ Fragments\nwhen playing a Conflict Side song",),
    "frag_plus_5_side_light": ("Earn +%@ Fragments\nwhen playing a Light Side song",),
    "frag_rng_ayu": ("Random Fragment bonus upon\ncompleting song",),
    "frags_kou": ("Earn up to +%@% Fragments\nbased on score",),
    "frags_nami": ("Earn 1 Fragment per %@ PURE notes\nLose 1 Fragment per LOST note",),
    "frags_nono": ("Earn +%@ Fragments for achieving\n%2@ grade or above",),
    "frags_ongeki": ("O.N.G.E.K.I. - Fragment reward on\ndealing Overdamage",),
    "frags_ongeki_hard": ("HARD + O.N.G.E.K.I. (50)",),
    "frags_ongeki_slash": ("O.N.G.E.K.I. - On Track Complete,\ndeal Overdamage based on accuracy",),
    "frags_preferred_song": ("Earn +%@ Fragments\nupon clearing a preferred song",),
    "frags_yume": ("Earn up to +%2@ Fragments based on Max Recall\nEarn +%@ Fragments on Clear",),
    "gauge_areus": ("HARD + LOST notes decrease Recollection Rate\nbased on current combo",),
    "gauge_chuni": ("CHUNITHM - Clear Requirement: 7",),
    "gauge_easy": ("EASY - Recollection Rate loss reduced\nfor LOST notes",),
    "gauge_easy|frag_plus_15_pst&prs": ("EASY + Earn +%@ Fragments\nwhen playing a %2@ song",),
    "gauge_easy|note_mirror": ("EASY + All Notes and Arcs reversed",),
    "gauge_exhaustion": ("Recollection Rate gain increased,\nbut decreases with song progress",),
    "gauge_hard": ("HARD - Track Lost when Recollection Rate\nreaches 0%",),
    "gauge_hard|fail_frag_minus_100": ("HARD + Lose %@ Fragments on Track Lost",),
    "gauge_hard|note_mirror": ("HARD + MIRROR - Track Lost when\nRecollection Rate reaches 0%",),
    "gauge_haruna": ("Recollection Gauge starts at %@%\nRecollection Rate gain reduced to %2@%",),
    "gauge_ilith_summer": ("HARD + Recollection Rate gain disabled\nwhen below %@ combo",),
    "gauge_isabelle": (
        "HARD + Max Recollection Gauge decreases\nbased on current Recollection Rate",
    ),
    "gauge_overflow": ("OVERFLOW - EASY Recollection Rate \nHARD upon reaching 100% Recollection",),
    "gauge_pandora": ("HARD - Track Lost after %@ LOST notes",),
    "gauge_regulus": ("HARD + FAR notes slightly decrease\nRecollection Rate",),
    "gauge_safe_10": ("No Recollection Rate loss for\nthe first %@ LOST notes",),
    "gauge_saya": (
        "Increased Recollection Rate change per note\nNo Recollection Rate gain for FAR notes",
    ),
    "gauge_seele": ("HARD + Recollection Rate gain disabled\nfor the last 1/4 of song",),
    "gauge_tempest": ("HARD - Tempest Gauge",),
    "gaugestart_30|gaugegain_70": (
        "EASY - Recollection Gauge starts at %@%\nReduced Recollection Rate gain per note",
    ),
    "ilith_awakened_skill": (
        "HARD + 6% chance to lose 6x Recollection Rate\nSTEP increased by 6 on clear",
    ),
    "kantandeshou": ("Earn +%@ Fragments on\nPure Memory (Max Score)",),
    "luna_uncap": ("World progress increased by\n%@ when starting on a Restriction Step",),
    "note_mirror": ("MIRROR - All Notes and Arcs reversed",),
    "note_mirror|visual_hide_far": ("MIRROR + FAR judgements hidden",),
    "omatsuri_daynight": ("Day / Night appearance\nwhen playing a %@ song",),
    "scoreclear_aa|visual_scoregauge": (
        "Recollection Gauge measures Grade\n(Track Lost on Grade A or below)",
    ),
    "shirabe_entry_fee": (
        "Pay the chart level in Fragments on start\nEarn +10 Fragments on EX or above",
    ),
    "skill_acid": ("HARD + For every 1/5 of song progress\n-10 Recollection Rate, +2 Fragments",),
    "skill_aichan": ("Recommends songs daily. Gain 41 Fragments\non first clear of each song",),
    "skill_amane": (
        "Ignore Speed and Random Restriction Steps,\nWorld progress halved below Grade EX",
    ),
    "skill_chinatsu": ("O.N.G.E.K.I. - Boost random stats\non dealing Overdamage",),
    "skill_doroc_uncap": (
        "Recollection Gauge measures Grade (Track Lost\nwhen grade falls below personal best)",
    ),
    "skill_elizabeth": (
        "Earn +%@ Fragments (increases for each\nconsecutive play with this Partner)",
    ),
    "skill_eto_hoppe": ("World progress doubled when Stamina\nis greater than or equal to 6",),
    "skill_fatalis": ("HARD - Fatalis Gauge + sacrifices stamina\nto overload World Mode",),
    "skill_frag_doubled_after_earning_X": (
        "Fragment gain doubled upon earning\n%1@ Fragments using other Partners",
        "On next song play,\nFragment gain is doubled",
    ),
    "skill_hikari_clear": ("FEVER GAUGE + Earn 1 Fragment when\nFEVER reaches x5",),
    "skill_hikari_selene": ("CHUNITHM + HARD - STEP and OVER\nincreased by 2 per each full gauge",),
    "skill_hikari_tairitsu_debut": (
        "Gain +20 on all stats on first\nArcaea Next Stage song play daily",
    ),
    "skill_hikari_vanessa": (
        "HARD + Lose Emotions. Weaken an aspect of\nHikari & Vanessa by -10 per Emotion lost",
    ),
    "skill_hp_slow_drain": ("HARD + Recollection Rate gradually decreases\nwith song progress",),
    "skill_hprate_based_on_hp": (
        "Recollection Rate gain reduces above 50%\nand increases below 50%",
    ),
    "skill_ilith_ivy": ("Recall Emotions. Each Emotion\nboosts an aspect of Ilith & Ivy by +10",),
    "skill_insight_konzetsu": ("HARD - Echelon %1@ Nullified Gauge\n+ Judgment effect altered",),
    "skill_intruder": (
        "HARD - Irruption Gauge - Chance to usurp\nPartners' World plays with 2x progress",
        "Her power is currently restrained.\nInsight cannot usurp Partners' World plays.",
        "HARD - Irruption Gauge",
    ),
    "skill_kanae_midsummer": (
        "EASY + Pay %@ Fragments on start\nThis skill changes during the night",
        "HARD + Gain +%@ Fragments on Track Clear\nThis skill changes during the day",
    ),
    "skill_kanae_uncap": (
        "STEP progress carries over to the next World\nplay when using Stamina (Current: %@)",
    ),
    "skill_kou_winter": (
        "Partners share %@% of their Fragments with Kou,\n"
        "received after playing a song (Total: %2@)",
    ),
    "skill_lagrange": ("Score displays distance\nto closest Grade threshold",),
    "skill_lily": (
        "Earn +%@ Fragments (increases for each\nconsecutive play with other Partners)",
    ),
    "skill_lost_to_85": ("At or above 90% Recollection Rate\nLOST notes reduce Rate to 85%",),
    "skill_luin": ("HARD + Earn +%@ Fragments\nReward increases for consecutive clears",),
    "skill_luin_uncap": (
        "HARD - Gauge persists + Earn +%@ Fragments\nReward increases for consecutive clears",
    ),
    "skill_luna_ilot": ("Earn up to 20 Fragments based on\nnumber of notes hit",),
    "skill_maya": (
        "Ignore Random Restriction Steps\nAfter World progress, this skill changes",
        "RESTRICTION - Random + Double World progress\nAfter World progress, this skill changes",
    ),
    "skill_maya_uncap": ("Recollection Rate at 1/4 song progress\nis converted to stat bonus",),
    "skill_mika": ("Stats are temporarily doubled\nupon clearing a maimai song",),
    "skill_milk": (
        "Use all Milk (Current: %@). Each Milk grants\na +11% chance to gain 100 Fragments",
    ),
    "skill_mithra": ("HARD + World Mode progress increased by 1\nfor each %@ combo reached",),
    "skill_nai": ("When 5 notes are LOST, FRAG reduced by 3\nper additional LOST note",),
    "skill_nami_sui": (
        "FEVER Gauge + World progress increased based\non PURE note count and FEVER level",
    ),
    "skill_nami_twilight": (
        "EASY + Recollection Rate cannot decrease\nRecollection Rate gain is heavily reduced",
    ),
    "skill_nell": ("HARD - Forlorn Gauge",),
    "skill_nonoka": (
        "Gain or lose Rank based on performance\nRisk and Reward increase at higher Ranks",
        "Rank %1@: Earn +%2@% Fragments,\nx%3@ Recollection Rate loss",
    ),
    "skill_nonoka_uncap": (
        "Performance does not effect ascent or descent\nUpon failure, all will be lost",
        "%1@ Gain +%2@% World progress,\nx%3@ Recollection Rate loss",
    ),
    "skill_reunion": (
        "CONFLICT - Reverse the paradigms\nof Light and Conflict.",
        "LIGHT - Rewrite the paradigms\nof Light and Conflict.",
    ),
    "skill_salt": ("World progress increased by up to 10\nbased on completed Maps in a Chapter",),
    "skill_saya_konzetsu": ("HARD - Endure Fate",),
    "skill_saya_uncap": ("Note judgement details displayed",),
    "skill_selene": (
        "HARD + Gain 10 STEP for every 1/3rd of total\nnote count that max combo reaches",
    ),
    "skill_shama": ("Pay 10 Fragments on start\nGain 1 Milk on clear",),
    "skill_shikoku": ("HARD + Increased Recollection Rate\nchange per note",),
    "skill_tairitsu_fail": (
        "FEVER GAUGE + HARD - Recollection Rate gain\nreduced when FEVER is low",
    ),
    "skill_toa": ("HARD - Track Lost after %@ FAR or LOST notes",),
    "skill_tsumugi": ("O.N.G.E.K.I. - Reward Overdamage fragments\nbased on performance",),
    "skill_vita": ("HARD + MIRROR - OVER increased by\nup to %@ based on Recollection Rate",),
    "skill_vita_arc": ("Recollection Gauge and OVER reduced by 1\nfor every 2 FAR notes",),
    "sometimes(note_mirror|frag_plus_5)": (
        "Randomly triggers MIRROR\nGain +%@ Fragments on MIRROR",
    ),
    "visual_ghost_skynotes": (
        "MUSE DASH - Sky Notes become ghosts\nwhen playing a Muse Dash song",
    ),
    "visual_hide_hp": ("VISUAL - Recollection Gauge is hidden",),
    "visual_ink": ("Sense of Incompleteness",),
    "visual_tomato_pack_tonesphere": (
        "VISUAL - 'Nutritious' note appearance\nwhen playing a %2@ song",
    ),
}
